### ISSUE TITLE
Setting REGOUT0 in merged.hex

### ISSUE THREAD

**Issue by mondalaci** [UltimateHackingKeyboard/firmware-uhk80#361]
@benedekkupper Please see this Nordic thread: https://devzone.nordicsemi.com/f/nordic-q-a/116490/setting-regout0-in-merged-hex/511242

Can you help with this? The suggested approach is not the cleanest, and the build fails when I try to use it. The cleanest Zephyr-native approach is preferred if implemented in a reasonable timeframe.

**Comment by benedekkupper** [comment]
Merged in #353
